<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[2]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[3]=array(0,1,1,'5bel56iL5qGI5L6L');
$cfg_Cs[4]=array(0,1,1,'5Yqe5YWs5a625YW3');
$cfg_Cs[5]=array(0,1,1,'6KOF5L+u55+l6K+G');
$cfg_Cs[6]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[7]=array(0,1,1,'5oub6LSk57qz5aOr');
$cfg_Cs[8]=array(0,1,1,'5pyN5Yqh5rWB56iL');
$cfg_Cs[9]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[13]=array(0,1,1,'5bm754Gv54mH');
$cfg_Cs[10]=array(0,1,1,'5YWs5Y+46I2j6KqJ');
$cfg_Cs[11]=array(0,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[12]=array(0,1,1,'6K6+6K6h5YmN5rK/');
?>