<?php
$z[0]=Array("channel","\r\n          <li><a href='[field:typelink/]' title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n        ",182,338);
$z[0][4]['type']="top";
$z[0][4]['row']="5";
$z[1]=Array("global","",561,582);
$z[1][4]['name']="cfg_mc";
$z[2]=Array("global","",622,643);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",674,695);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",726,747);
$z[4][4]['name']="cfg_yx";

?>