<?php
$z[0]=Array("channelartlist","\r\n      <li class=\"nav_li\"><a href=\"{dede:field name='typeurl'/}\" class=\"menu\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <ul class=\"sub_nav\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typelink/]\" target=\"_self\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n      </li>\r\n      ",706,1146);
$z[0][4]['row']="8";
$z[0][4]['typeid']="top";
$z[1]=Array("arclist","\r\n      <li><a href=\"/\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"\" width=\"980\" height=\"350\"/></a></li>\r\n      ",1232,1412);
$z[1][4]['row']="5";
$z[1][4]['titlelen']="36";
$z[1][4]['typeid']="13";
$z[2]=Array("arclist","<a href=\"[field:arcurl /]\" title =\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a> <span> [field:pubdate function=strftime('%y/%m/%d',@me)/]</span>",1770,2020);
$z[2][4]['typeid']="11";
$z[2][4]['limit']="0,1";
$z[2][4]['titlelen']="34";
$z[2][4]['flag']="c";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("arclist","<a href=\"[field:arcurl /]\" title =\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a> <span> [field:pubdate function=strftime('%y/%m/%d',@me)/]</span>",2075,2325);
$z[3][4]['typeid']="11";
$z[3][4]['limit']="1,1";
$z[3][4]['titlelen']="34";
$z[3][4]['flag']="c";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","<a href=\"[field:arcurl /]\" title =\"[field:fulltitle/]\" target=\"_blank\">[field:title/]</a> <span> [field:pubdate function=strftime('%y/%m/%d',@me)/]</span>",2380,2630);
$z[4][4]['typeid']="11";
$z[4][4]['limit']="2,1";
$z[4][4]['titlelen']="34";
$z[4][4]['flag']="c";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",4620,4647);
$z[5][4]['name']="phpurl";

?>